name: biogtr
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pytorch-cuda=11.8
  - cudnn
  - pytorch
  - torchvision
  - lightning
  - imageio
  - av
  - ffmpeg
  - albumentations
  - pip
  - torchaudio
  - imageio-ffmpeg
  - ca-certificates
  - certifi
  - openssl